name: Push Trigger Demo

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Message
        run: echo "Push Trigger Executed Successfully"

      - name: Display Date
        run: date
